"""
Default Powers (abilities) for Legends of Learning — Warrior / Sorcerer / Druid themes.
Seeded when the abilities table is empty. prerequisite is the name of another power in this list.
"""

ABILITY_DATA = [
    # --- Warrior ---
    {
        "name": "Shield Wall",
        "description": "Classroom: stand your ground — small personal protection. Game: +5 defense to yourself for a short time.",
        "type": "defense",
        "level_requirement": 1,
        "power": 5,
        "cost": 2,
        "cooldown": 0,
        "duration": 5,
        "tier": "basic",
        "class_restriction": "Warrior",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Battle Cry",
        "description": "Rally a teammate — they gain a burst of focus (power). Game: +3 power to one ally.",
        "type": "buff",
        "level_requirement": 2,
        "power": 3,
        "cost": 3,
        "cooldown": 0,
        "duration": 5,
        "tier": "basic",
        "class_restriction": "Warrior",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Seat Swap",
        "description": "Real-world privilege: move to an open seat when the teacher allows.",
        "type": "utility",
        "level_requirement": 3,
        "power": 0,
        "cost": 3,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Warrior",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Protect Ally",
        "description": "Shield a teammate from the next rough moment. Game: +8 defense to one ally.",
        "type": "defense",
        "level_requirement": 4,
        "power": 8,
        "cost": 4,
        "cooldown": 0,
        "duration": 5,
        "tier": "basic",
        "class_restriction": "Warrior",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Shield Wall",
    },
    {
        "name": "Fortify",
        "description": "Brace the whole team. Game: +10 defense to all allies in your clan.",
        "type": "defense",
        "level_requirement": 6,
        "power": 10,
        "cost": 5,
        "cooldown": 0,
        "duration": 5,
        "tier": "advanced",
        "class_restriction": "Warrior",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Protect Ally",
    },
    {
        "name": "Frontal Assault",
        "description": "Team homework pass — teacher-defined real-world reward.",
        "type": "utility",
        "level_requirement": 8,
        "power": 0,
        "cost": 6,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": "Warrior",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Fortify",
    },
    {
        "name": "Iron Will",
        "description": "Shake off a small setback. Game: strong personal defense buff.",
        "type": "defense",
        "level_requirement": 10,
        "power": 12,
        "cost": 4,
        "cooldown": 0,
        "duration": 8,
        "tier": "advanced",
        "class_restriction": "Warrior",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Battle Cry",
    },
    {
        "name": "Last Stand",
        "description": "Real-world: help a teammate avoid the worst outcome when they’d hit 0 HP. Game: big protect buff.",
        "type": "defense",
        "level_requirement": 13,
        "power": 15,
        "cost": 8,
        "cooldown": 0,
        "duration": 10,
        "tier": "elite",
        "class_restriction": "Warrior",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Fortify",
    },
    {
        "name": "Unbreakable",
        "description": "The team holds the line together. Game: +15 defense to all allies.",
        "type": "buff",
        "level_requirement": 16,
        "power": 15,
        "cost": 10,
        "cooldown": 0,
        "duration": 6,
        "tier": "elite",
        "class_restriction": "Warrior",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Last Stand",
    },
    # --- Sorcerer ---
    {
        "name": "Arcane Spark",
        "description": "Sharpen your own focus. Game: +3 power to yourself.",
        "type": "buff",
        "level_requirement": 1,
        "power": 3,
        "cost": 2,
        "cooldown": 0,
        "duration": 5,
        "tier": "basic",
        "class_restriction": "Sorcerer",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Mana Transfer",
        "description": "Share energy with a teammate. Game: +5 power to one ally.",
        "type": "buff",
        "level_requirement": 2,
        "power": 5,
        "cost": 4,
        "cooldown": 0,
        "duration": 5,
        "tier": "basic",
        "class_restriction": "Sorcerer",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Teleport",
        "description": "Real-world: short hall pass (e.g. 2 minutes) for materials or restroom.",
        "type": "utility",
        "level_requirement": 3,
        "power": 0,
        "cost": 3,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Sorcerer",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Invisibility",
        "description": "Real-world: exempt from cold-call for a day (teacher-defined).",
        "type": "utility",
        "level_requirement": 5,
        "power": 0,
        "cost": 4,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Sorcerer",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Arcane Spark",
    },
    {
        "name": "Power Surge",
        "description": "Big boost for a struggling ally. Game: +8 power to one ally.",
        "type": "buff",
        "level_requirement": 7,
        "power": 8,
        "cost": 6,
        "cooldown": 0,
        "duration": 6,
        "tier": "advanced",
        "class_restriction": "Sorcerer",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Mana Transfer",
    },
    {
        "name": "Mana Shield",
        "description": "Convert focus into protection. Game: defense buff on self.",
        "type": "defense",
        "level_requirement": 9,
        "power": 8,
        "cost": 5,
        "cooldown": 0,
        "duration": 6,
        "tier": "advanced",
        "class_restriction": "Sorcerer",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Arcane Spark",
    },
    {
        "name": "Time Warp",
        "description": "Real-world: earn an extra class game or bonus activity (teacher-defined).",
        "type": "utility",
        "level_requirement": 11,
        "power": 0,
        "cost": 7,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": "Sorcerer",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Power Surge",
    },
    {
        "name": "Arcane Mastery",
        "description": "Elevate the whole team’s focus. Game: +10 power to all allies.",
        "type": "buff",
        "level_requirement": 14,
        "power": 10,
        "cost": 9,
        "cooldown": 0,
        "duration": 6,
        "tier": "elite",
        "class_restriction": "Sorcerer",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Power Surge",
    },
    {
        "name": "Fountain of Mana",
        "description": "Fully restore one teammate’s power (focus) for the next stretch.",
        "type": "utility",
        "level_requirement": 17,
        "power": 0,
        "cost": 12,
        "cooldown": 0,
        "duration": 1,
        "tier": "elite",
        "class_restriction": "Sorcerer",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Arcane Mastery",
        "special_effect": "restore_power_full",
    },
    # --- Druid ---
    {
        "name": "Minor Heal",
        "description": "Help a teammate recover. Game: heal 10 HP on one ally.",
        "type": "heal",
        "level_requirement": 1,
        "power": 10,
        "cost": 2,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Druid",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Snack Time",
        "description": "Real-world: eat a snack in class when allowed.",
        "type": "utility",
        "level_requirement": 2,
        "power": 0,
        "cost": 2,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Druid",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Nature's Touch",
        "description": "Center yourself. Game: heal 15 HP on yourself.",
        "type": "heal",
        "level_requirement": 3,
        "power": 15,
        "cost": 3,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Druid",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Minor Heal",
    },
    {
        "name": "Herbal Remedy",
        "description": "Real-world: use notes on a quiz/test when the teacher allows.",
        "type": "utility",
        "level_requirement": 4,
        "power": 0,
        "cost": 3,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": "Druid",
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Snack Time",
    },
    {
        "name": "Greater Heal",
        "description": "Strong recovery for a teammate. Game: heal 25 HP.",
        "type": "heal",
        "level_requirement": 6,
        "power": 25,
        "cost": 5,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": "Druid",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Minor Heal",
    },
    {
        "name": "Healing Circle",
        "description": "Support the whole clan. Game: heal 15 HP on each ally.",
        "type": "heal",
        "level_requirement": 9,
        "power": 15,
        "cost": 7,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": "Druid",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Greater Heal",
    },
    {
        "name": "Revive",
        "description": "Real-world: second chance when a teammate hits 0 HP. Game: bring ally to 1 HP.",
        "type": "heal",
        "level_requirement": 11,
        "power": 1,
        "cost": 8,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": "Druid",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Healing Circle",
        "special_effect": "revive",
    },
    {
        "name": "Nature's Blessing",
        "description": "Major recovery for one ally. Game: heal 40 HP.",
        "type": "heal",
        "level_requirement": 14,
        "power": 40,
        "cost": 10,
        "cooldown": 0,
        "duration": 1,
        "tier": "elite",
        "class_restriction": "Druid",
        "target_type": "single_ally",
        "pp_cost": 1,
        "prerequisite": "Greater Heal",
    },
    {
        "name": "Rejuvenation",
        "description": "Restore the whole team. Game: full heal all allies in clan.",
        "type": "heal",
        "level_requirement": 17,
        "power": 0,
        "cost": 12,
        "cooldown": 0,
        "duration": 1,
        "tier": "elite",
        "class_restriction": "Druid",
        "target_type": "all_allies",
        "pp_cost": 1,
        "prerequisite": "Healing Circle",
        "special_effect": "full_heal",
    },
    # --- Universal (any class) ---
    {
        "name": "Quick Rest",
        "description": "Real-world: short break (e.g. stretch, water).",
        "type": "utility",
        "level_requirement": 5,
        "power": 0,
        "cost": 3,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": None,
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": None,
    },
    {
        "name": "Study Buddy",
        "description": "Real-world: pick your partner for paired work.",
        "type": "utility",
        "level_requirement": 7,
        "power": 0,
        "cost": 4,
        "cooldown": 0,
        "duration": 1,
        "tier": "basic",
        "class_restriction": None,
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Quick Rest",
    },
    {
        "name": "Music Pass",
        "description": "Real-world: headphones / quiet music during independent work.",
        "type": "utility",
        "level_requirement": 10,
        "power": 0,
        "cost": 5,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": None,
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Study Buddy",
    },
    {
        "name": "Late Pass",
        "description": "Real-world: turn in one assignment one day late for full credit.",
        "type": "utility",
        "level_requirement": 13,
        "power": 0,
        "cost": 6,
        "cooldown": 0,
        "duration": 1,
        "tier": "advanced",
        "class_restriction": None,
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Music Pass",
    },
    {
        "name": "Teacher's Pet",
        "description": "Real-world: positive note or call home (teacher-defined).",
        "type": "utility",
        "level_requirement": 16,
        "power": 0,
        "cost": 8,
        "cooldown": 0,
        "duration": 1,
        "tier": "elite",
        "class_restriction": None,
        "target_type": "self",
        "pp_cost": 1,
        "prerequisite": "Late Pass",
    },
]


def seed_default_abilities(db, ability_model):
    """
    Insert default abilities and wire prerequisites. Idempotent if rows already exist.
    """
    if ability_model.query.count() > 0:
        return
    name_to_row = {}
    for item in ABILITY_DATA:
        row = ability_model(
            name=item["name"],
            type=item["type"],
            description=item.get("description"),
            level_requirement=item["level_requirement"],
            power=item["power"],
            cost=item["cost"],
            cooldown=item.get("cooldown", 0),
            duration=item.get("duration", 1),
            tier=item["tier"],
            class_restriction=item.get("class_restriction"),
            target_type=item.get("target_type", "self"),
            pp_cost=item.get("pp_cost", 1),
            is_default=True,
            created_by_teacher_id=None,
            prerequisite_id=None,
            special_effect=item.get("special_effect"),
        )
        db.session.add(row)
        name_to_row[item["name"]] = row
    db.session.flush()
    for item in ABILITY_DATA:
        prereq_name = item.get("prerequisite")
        if prereq_name:
            child = name_to_row[item["name"]]
            parent = name_to_row.get(prereq_name)
            if parent:
                child.prerequisite_id = parent.id
    db.session.commit()
