"""
Equipment Data Schema for Hardcoded Shop Items

To add a new equipment item, add a new dictionary entry to the appropriate list below.

Fields:
- name: str
- description: str
- type: EquipmentType (WEAPON, ARMOR, ACCESSORY)
- slot: EquipmentSlot (MAIN_HAND, CHEST, RING, etc.)
- cost: int
- level_requirement: int
- health_bonus: int
- power_bonus: int
- defense_bonus: int
- rarity: int (1=common, 2=uncommon, ...)
- image_url: str (relative to /static/images/equipment/...)
- class_restriction: Optional[str] (e.g., 'warrior', 'sorcerer', 'druid')

Example entry:
{
    'name': 'Training Sword',
    'description': 'A basic sword for warriors in training',
    'type': EquipmentType.WEAPON,
    'slot': EquipmentSlot.MAIN_HAND,
    'cost': 100,
    'level_requirement': 1,
    'health_bonus': 0,
    'power_bonus': 5,
    'defense_bonus': 0,
    'rarity': 1,
    'image_url': '/static/images/equipment/warrior/warrior 1 Weapon Sword.png',
    'class_restriction': 'sorcerer',
}
"""

from app.models.equipment import EquipmentType, EquipmentSlot

EQUIPMENT_DATA = [
    # --- Warrior ---
    {
        'name': 'Warrior Ring',
        'description': 'A ring for warriors, enhances resilience.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 2,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior 1 Accessory Ring.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Leather Armor',
        'description': 'Basic leather armor for warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 10,
        'power_bonus': 0,
        'defense_bonus': 5,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior 1 Armor Leather.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Plate Armor',
        'description': 'Heavy plate armor for advanced warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 15,
        'power_bonus': 0,
        'defense_bonus': 8,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior 1 Armor Plate.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Shield',
        'description': 'A shield for warriors, provides extra defense.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 0,
        'defense_bonus': 10,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior 1 Accessory Shield.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Bow',
        'description': 'A bow for skilled warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 150,
        'level_requirement': 2,
        'health_bonus': 0,
        'power_bonus': 4,
        'defense_bonus': 2,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior 2 Weapon Bow.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Axe',
        'description': 'A basic axe for warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 6,
        'defense_bonus': -1,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior 1 Weapon Axe.png',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Sword',
        'description': 'A basic sword for warriors in training.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 5,
        'defense_bonus': 0,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior 1 Weapon Sword.png',
        'class_restriction': 'warrior',
    },
    # --- Sorcerer ---
    {
        'name': 'Sorcerer Book',
        'description': 'A magical book for sorcerers.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 8,
        'defense_bonus': 2,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Accessory Book.png',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Wand',
        'description': 'A basic wand for sorcerers.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 4,
        'defense_bonus': 1,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Weapon Wand.png',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak II',
        'description': 'An advanced cloak for sorcerers.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 8,
        'power_bonus': 8,
        'defense_bonus': 0,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Armor Cloak2.png',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Staff',
        'description': 'A basic staff for sorcerers.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 3,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Weapon Staff.png',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Ring',
        'description': 'A ring that enhances magical abilities.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 3,
        'power_bonus': 5,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Accessory Ring.png',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak',
        'description': 'A basic cloak for sorcerers.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 5,
        'defense_bonus': 0,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer 1 Armor Cloak.png',
        'class_restriction': 'sorcerer',
    },
    # --- Druid ---
    {
        'name': 'Druid Bracers',
        'description': 'Bracers that enhance natural abilities.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 6,
        'power_bonus': 2,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid 1 Accessory Bracers.png',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Flail',
        'description': 'A flail imbued with natural magic.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 3,
        'power_bonus': 4,
        'defense_bonus': 3,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid 1 Weapon Flail.png',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak II',
        'description': 'An enchanted cloak for druids.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 12,
        'power_bonus': 3,
        'defense_bonus': 7,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid 1 Armor Cloak2.png',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Staff',
        'description': 'A staff imbued with natural magic.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 2,
        'defense_bonus': 3,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid 1 Weapon Staff.png',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Pendant',
        'description': 'A pendant that enhances natural magic.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.NECK,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 4,
        'power_bonus': 4,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid 1 Accessory Pendant.png',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak',
        'description': 'A basic cloak for druids.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 8,
        'power_bonus': 2,
        'defense_bonus': 5,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid 1 Armor Cloak.png',
        'class_restriction': 'druid',
    },
] 