"""
Equipment Data Schema for Hardcoded Shop Items

To add a new equipment item, add a new dictionary entry to the appropriate list below.

Fields:
- name: str
- description: str
- type: EquipmentType (WEAPON, ARMOR, ACCESSORY)
- slot: EquipmentSlot (MAIN_HAND, CHEST, RING, etc.)
- cost: int
- level_requirement: int
- health_bonus: int
- power_bonus: int
- defense_bonus: int
- rarity: int (1=common, 2=uncommon, ...)
- image_url: str (relative to /static/images/equipment/...)
- class_restriction: Optional[str] (e.g., 'warrior', 'sorcerer', 'druid')

Example entry:
{
    'name': 'Training Sword',
    'description': 'A basic sword for warriors in training',
    'type': EquipmentType.WEAPON,
    'slot': EquipmentSlot.MAIN_HAND,
    'cost': 100,
    'level_requirement': 1,
    'health_bonus': 0,
    'power_bonus': 5,
    'defense_bonus': 0,
    'rarity': 1,
    'image_url': '/static/images/equipment/warrior/warrior_1_weapon_sword.png',
    'class_restriction': 'sorcerer',
}
"""

from app.models.equipment import EquipmentType, EquipmentSlot

EQUIPMENT_DATA = [
    # --- Warrior ---
    {
        'name': 'Warrior Ring',
        'description': 'A ring for warriors, enhances resilience.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 2,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior_1_accessory_ring.png',
        'catalogue_key': 'warrior_1_accessory_ring',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Leather Armor',
        'description': 'Basic leather armor for warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 10,
        'power_bonus': 0,
        'defense_bonus': 5,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior_1_armor_leather.png',
        'catalogue_key': 'warrior_1_armor_leather',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Plate Armor',
        'description': 'Heavy plate armor for advanced warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 15,
        'power_bonus': 0,
        'defense_bonus': 8,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_1_armor_plate.png',
        'catalogue_key': 'warrior_1_armor_plate',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Shield',
        'description': 'A shield for warriors, provides extra defense.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 0,
        'defense_bonus': 10,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_1_accessory_shield.png',
        'catalogue_key': 'warrior_1_accessory_shield',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Bow',
        'description': 'A bow for skilled warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 150,
        'level_requirement': 2,
        'health_bonus': 0,
        'power_bonus': 4,
        'defense_bonus': 2,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_weapon_bow.png',
        'catalogue_key': 'warrior_2_weapon_bow',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Axe',
        'description': 'A basic axe for warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 6,
        'defense_bonus': -1,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior_1_weapon_axe.png',
        'catalogue_key': 'warrior_1_weapon_axe',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Sword',
        'description': 'A basic sword for warriors in training.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 5,
        'defense_bonus': 0,
        'rarity': 1,
        'image_url': '/static/images/equipment/warrior/warrior_1_weapon_sword.png',
        'catalogue_key': 'warrior_1_weapon_sword',
        'class_restriction': 'warrior',
    },
    # --- Sorcerer ---
    {
        'name': 'Sorcerer Book',
        'description': 'A magical book for sorcerers.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 8,
        'defense_bonus': 2,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_accessory_book.png',
        'catalogue_key': 'sorcerer_1_accessory_book',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Wand',
        'description': 'A basic wand for sorcerers.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 4,
        'defense_bonus': 1,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_weapon_wand.png',
        'catalogue_key': 'sorcerer_1_weapon_wand',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak I',
        'description': 'An advanced cloak for sorcerers.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 8,
        'power_bonus': 8,
        'defense_bonus': 0,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_armor_cloak2.png',
        'catalogue_key': 'sorcerer_1_armor_cloak2',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Staff',
        'description': 'A basic staff for sorcerers.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 0,
        'power_bonus': 3,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_weapon_staff.png',
        'catalogue_key': 'sorcerer_1_weapon_staff',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Ring',
        'description': 'A ring that enhances magical abilities.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 3,
        'power_bonus': 5,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_accessory_ring.png',
        'catalogue_key': 'sorcerer_1_accessory_ring',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak',
        'description': 'A basic cloak for sorcerers.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 5,
        'defense_bonus': 0,
        'rarity': 1,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_1_armor_cloak.png',
        'catalogue_key': 'sorcerer_1_armor_cloak',
        'class_restriction': 'sorcerer',
    },
    # --- Druid ---
    {
        'name': 'Druid Bracers',
        'description': 'Bracers that enhance natural abilities.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 250,
        'level_requirement': 1,
        'health_bonus': 6,
        'power_bonus': 2,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_1_accessory_bracers.png',
        'catalogue_key': 'druid_1_accessory_bracers',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Flail',
        'description': 'A flail imbued with natural magic.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 3,
        'power_bonus': 4,
        'defense_bonus': 3,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_1_weapon_flail.png',
        'catalogue_key': 'druid_1_weapon_flail',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak I',
        'description': 'An enchanted cloak for druids.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 12,
        'power_bonus': 3,
        'defense_bonus': 7,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_1_armor_cloak2.png',
        'catalogue_key': 'druid_1_armor_cloak2',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Staff',
        'description': 'A staff imbued with natural magic.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 100,
        'level_requirement': 1,
        'health_bonus': 5,
        'power_bonus': 2,
        'defense_bonus': 3,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid_1_weapon_staff.png',
        'catalogue_key': 'druid_1_weapon_staff',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Pendant',
        'description': 'A pendant that enhances natural magic.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.NECK,
        'cost': 200,
        'level_requirement': 1,
        'health_bonus': 4,
        'power_bonus': 4,
        'defense_bonus': 2,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid_1_accessory_pendant.png',
        'catalogue_key': 'druid_1_accessory_pendant',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak',
        'description': 'A basic cloak for druids.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 150,
        'level_requirement': 1,
        'health_bonus': 8,
        'power_bonus': 2,
        'defense_bonus': 5,
        'rarity': 1,
        'image_url': '/static/images/equipment/druid/druid_1_armor_cloak.png',
        'catalogue_key': 'druid_1_armor_cloak',
        'class_restriction': 'druid',
    },
    
    # --- Warrior Tier 2 ---
    {
        'name': 'Warrior Ring II',
        'description': 'An enhanced ring for warriors, greatly increases resilience.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 10,
        'power_bonus': 4,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_accessory_ring.png',
        'catalogue_key': 'warrior_2_accessory_ring',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Shield II',
        'description': 'An advanced shield for warriors, superior defense.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 500,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 0,
        'defense_bonus': 20,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_accessory_shield.png',
        'catalogue_key': 'warrior_2_accessory_shield',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Plate Armor II',
        'description': 'Reinforced plate armor for seasoned warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 30,
        'power_bonus': 0,
        'defense_bonus': 16,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_armor_plate.png',
        'catalogue_key': 'warrior_2_armor_plate',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Axe II',
        'description': 'A battle-worn axe for experienced warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 12,
        'defense_bonus': -2,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_weapon_axe.png',
        'catalogue_key': 'warrior_2_weapon_axe',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Sword II',
        'description': 'A tempered sword for veteran warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 10,
        'defense_bonus': 0,
        'rarity': 2,
        'image_url': '/static/images/equipment/warrior/warrior_2_weapon_sword.png',
        'catalogue_key': 'warrior_2_weapon_sword',
        'class_restriction': 'warrior',
    },
    
    # --- Warrior Tier 3 ---
    {
        'name': 'Warrior Shield III',
        'description': 'A legendary shield for master warriors, unbreakable defense.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 1000,
        'level_requirement': 21,
        'health_bonus': 0,
        'power_bonus': 0,
        'defense_bonus': 40,
        'rarity': 3,
        'image_url': '/static/images/equipment/warrior/warrior_3_accessory_shield.png',
        'catalogue_key': 'warrior_3_accessory_shield',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Plate Armor III',
        'description': 'Masterwork plate armor for legendary warriors.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 800,
        'level_requirement': 21,
        'health_bonus': 60,
        'power_bonus': 0,
        'defense_bonus': 32,
        'rarity': 3,
        'image_url': '/static/images/equipment/warrior/warrior_3_armor_plate.png',
        'catalogue_key': 'warrior_3_armor_plate',
        'class_restriction': 'warrior',
    },
    {
        'name': 'Warrior Sword III',
        'description': 'A legendary blade forged for champion warriors.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 600,
        'level_requirement': 21,
        'health_bonus': 0,
        'power_bonus': 20,
        'defense_bonus': 0,
        'rarity': 3,
        'image_url': '/static/images/equipment/warrior/warrior_3_weapon_sword.png',
        'catalogue_key': 'warrior_3_weapon_sword',
        'class_restriction': 'warrior',
    },
    
    # --- Sorcerer Tier 2 ---
    {
        'name': 'Sorcerer Book II',
        'description': 'An ancient tome of powerful spells for advanced sorcerers.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 500,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 16,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_2_accessory_book.png',
        'catalogue_key': 'sorcerer_2_accessory_book',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Ring II',
        'description': 'An enchanted ring that amplifies magical power.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.RING,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 6,
        'power_bonus': 10,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_2_accessory_ring.png',
        'catalogue_key': 'sorcerer_2_accessory_ring',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak II',
        'description': 'An enchanted cloak woven with arcane threads.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 16,
        'power_bonus': 16,
        'defense_bonus': 0,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_2_armor_cloak.png',
        'catalogue_key': 'sorcerer_2_armor_cloak',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Staff II',
        'description': 'A staff carved from ancient magical wood.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 6,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_2_weapon_staff.png',
        'catalogue_key': 'sorcerer_2_weapon_staff',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Wand II',
        'description': 'A refined wand for channeling advanced spells.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 0,
        'power_bonus': 8,
        'defense_bonus': 2,
        'rarity': 2,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_2_weapon_wand.png',
        'catalogue_key': 'sorcerer_2_weapon_wand',
        'class_restriction': 'sorcerer',
    },
    
    # --- Sorcerer Tier 3 ---
    {
        'name': 'Sorcerer Book III',
        'description': 'A legendary grimoire containing the most powerful spells.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 1000,
        'level_requirement': 21,
        'health_bonus': 0,
        'power_bonus': 32,
        'defense_bonus': 8,
        'rarity': 3,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_3_accessory_book.png',
        'catalogue_key': 'sorcerer_3_accessory_book',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Cloak III',
        'description': 'A masterwork cloak infused with pure arcane energy.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 800,
        'level_requirement': 21,
        'health_bonus': 32,
        'power_bonus': 32,
        'defense_bonus': 0,
        'rarity': 3,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_3_armor_cloak.png',
        'catalogue_key': 'sorcerer_3_armor_cloak',
        'class_restriction': 'sorcerer',
    },
    {
        'name': 'Sorcerer Staff III',
        'description': 'A legendary staff carved by archmages of old.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 600,
        'level_requirement': 21,
        'health_bonus': 0,
        'power_bonus': 12,
        'defense_bonus': 8,
        'rarity': 3,
        'image_url': '/static/images/equipment/sorcerer/sorcerer_3_weapon_staff.png',
        'catalogue_key': 'sorcerer_3_weapon_staff',
        'class_restriction': 'sorcerer',
    },
    
    # --- Druid Tier 2 ---
    {
        'name': 'Druid Bracers II',
        'description': 'Enhanced bracers that channel natural power.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.OFF_HAND,
        'cost': 500,
        'level_requirement': 11,
        'health_bonus': 12,
        'power_bonus': 4,
        'defense_bonus': 8,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_2_accessory_bracers.png',
        'catalogue_key': 'druid_2_accessory_bracers',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Pendant II',
        'description': 'A powerful pendant carved from ancient oak.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.NECK,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 8,
        'power_bonus': 8,
        'defense_bonus': 4,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_2_accessory_pendant.png',
        'catalogue_key': 'druid_2_accessory_pendant',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak II',
        'description': 'An enchanted cloak woven from blessed vines.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 400,
        'level_requirement': 11,
        'health_bonus': 24,
        'power_bonus': 6,
        'defense_bonus': 14,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_2_armor_cloak.png',
        'catalogue_key': 'druid_2_armor_cloak',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Flail II',
        'description': 'A flail blessed by the spirits of the forest.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 6,
        'power_bonus': 8,
        'defense_bonus': 6,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_2_weapon_flail.png',
        'catalogue_key': 'druid_2_weapon_flail',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Staff II',
        'description': 'A staff carved from the heartwood of an ancient tree.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 300,
        'level_requirement': 11,
        'health_bonus': 10,
        'power_bonus': 4,
        'defense_bonus': 6,
        'rarity': 2,
        'image_url': '/static/images/equipment/druid/druid_2_weapon_staff.png',
        'catalogue_key': 'druid_2_weapon_staff',
        'class_restriction': 'druid',
    },
    
    # --- Druid Tier 3 ---
    {
        'name': 'Druid Pendant III',
        'description': 'A legendary pendant imbued with primal magic.',
        'type': EquipmentType.ACCESSORY,
        'slot': EquipmentSlot.NECK,
        'cost': 800,
        'level_requirement': 21,
        'health_bonus': 16,
        'power_bonus': 16,
        'defense_bonus': 8,
        'rarity': 3,
        'image_url': '/static/images/equipment/druid/druid_3_accessory_pendant.png',
        'catalogue_key': 'druid_3_accessory_pendant',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Cloak III',
        'description': 'A masterwork cloak woven from the essence of nature itself.',
        'type': EquipmentType.ARMOR,
        'slot': EquipmentSlot.CHEST,
        'cost': 800,
        'level_requirement': 21,
        'health_bonus': 48,
        'power_bonus': 12,
        'defense_bonus': 28,
        'rarity': 3,
        'image_url': '/static/images/equipment/druid/druid_3_armor_cloak.png',
        'catalogue_key': 'druid_3_armor_cloak',
        'class_restriction': 'druid',
    },
    {
        'name': 'Druid Staff III',
        'description': 'A legendary staff that channels the full power of the wild.',
        'type': EquipmentType.WEAPON,
        'slot': EquipmentSlot.MAIN_HAND,
        'cost': 600,
        'level_requirement': 21,
        'health_bonus': 20,
        'power_bonus': 8,
        'defense_bonus': 12,
        'rarity': 3,
        'image_url': '/static/images/equipment/druid/druid_3_weapon_staff.png',
        'catalogue_key': 'druid_3_weapon_staff',
        'class_restriction': 'druid',
    },
]
